import type { Metadata } from "next";
import { setRequestLocale } from "next-intl/server";
import { ShieldCheck, FileSearch, Scale, RefreshCw, Eye, ListChecks, CalendarDays, ExternalLink, ArrowUpRight, Database, FileText, Building2, Smartphone, Tag, AlertTriangle } from "lucide-react";
import { Link } from "@/i18n/routing";
import { Container } from "@/components/ui/container";
import { absoluteUrl, localizedAlternates, type Locale } from "@/lib/site";

type Props = { params: Promise<{ locale: string }> };

const COPY = {
  tr: {
    metaTitle: "Araştırma ve Kaynak Politikası — VPN Advisor",
    metaDescription: "VPN Advisor'ın sağlayıcı bilgilerini nasıl topladığını, kaynak önceliğini, güncellik politikasını, karşılaştırma kriterlerini ve sınırlamalarını açıklayan şeffaf metodoloji.",
    badge: "Şeffaf kaynak politikası",
    h1: "VPN bilgilerini nasıl araştırıyor ve karşılaştırıyoruz?",
    intro: "VPN Advisor bir test laboratuvarı değildir ve gerçekleştirilmemiş hız, streaming veya güvenlik testlerini yapılmış gibi sunmaz. Amacımız; doğrulanabilir, güncel ve mümkün olduğunda birincil kaynaklardan gelen bilgileri anlaşılır bir karşılaştırma formatında düzenlemektir.",
    updated: "Son güncelleme", toc: "Bu sayfada",
    items: ["1. Temel ilke", "2. Kaynak hiyerarşisi", "3. Karşılaştırma alanları", "4. Güncellik", "5. Sınırlamalar ve gelir modeli"],
    principleTitle: "1. Temel ilke: iddia yerine kaynak",
    principleBody: "Bir sağlayıcı hakkında doğrulayamadığımız performans iddialarını puana dönüştürmüyoruz. Bir bilgi sağlayıcının resmi sayfasından geliyorsa bunu sağlayıcı beyanı olarak ele alırız; bağımsız bir denetim veya standart kuruluşu varsa kaynağın niteliğini ayrıca belirtiriz.",
    sourceTitle: "2. Kaynak hiyerarşisi", sourceIntro: "Bilgiyi mümkün olduğunda aşağıdaki sırayla doğrularız. Daha güçlü bir kaynak varken yalnızca pazarlama metnine dayanmayız.",
    sourceCards: [["Birincil kaynaklar", "Resmi teknik dokümantasyon, gizlilik politikaları, fiyat sayfaları, kullanım şartları ve uygulama mağazası kayıtları."], ["Bağımsız doğrulama", "Yayınlanmış no-logs denetimleri, güvenlik değerlendirmeleri, mahkeme/şirket kayıtları ve tanınmış standart kuruluşları."], ["İkincil kaynaklar", "Birincil kaynakların eksik olduğu durumlarda güvenilir teknik yayınlar ve kamuya açık araştırmalar; kaynak türü açıkça belirtilir."]],
    fieldsTitle: "3. Karşılaştırma alanları", fieldsIntro: "Sağlayıcı profilleri aynı bilgi başlıklarını kullanır. Bunlar kalite puanı değil, karşılaştırılabilir veri alanlarıdır.",
    fields: ["Şirket ve yargı yetkisi", "Gizlilik ve kayıt tutma politikası", "Bağımsız denetim veya güvence raporları", "Desteklenen protokoller ve teknik özellikler", "Cihaz ve platform desteği", "Fiyat, yenileme ve iade koşulları"],
    freshnessTitle: "4. Güncellik politikası", freshnessBody: "Fiyat ve ürün özellikleri hızlı değişebildiği için profillerde mümkün olduğunda son kontrol tarihi tutulur. Eski bir tarih gördüğünüzde resmi kaynağı kontrol etmeniz gerekir.",
    freshnessItems: ["Fiyat ve kampanyalar kalıcı veri kabul edilmez.", "Denetim bilgisi raporun yayın tarihi ve kapsamıyla birlikte değerlendirilir.", "Sunucu ve ülke sayıları sağlayıcı beyanıysa bu şekilde ele alınır.", "Önemli değişikliklerde ilgili sayfanın updatedAt tarihi yenilenir."],
    limitsTitle: "5. Sınırlamalar ve gelir modeli", limitsBody: "VPN performansı cihaz, ağ, ülke, protokol ve zamana göre değişir. Bu nedenle kamuya açık belgeler gerçek kullanıcı performansını garanti etmez. VPN Advisor Google AdSense ve ileride bazı ortaklık bağlantılarından gelir elde edebilir; bu ilişki veri alanlarını veya kaynak seçimini değiştirmemelidir.",
    limits: ["Sürekli laboratuvar hız testi yaptığımızı iddia etmiyoruz.", "Streaming erişimini kalıcı garanti olarak sunmuyoruz.", "Sağlayıcının kendi beyanını bağımsız doğrulama gibi göstermiyoruz.", "Fiyatların satın alma anında aynı kalacağını garanti etmiyoruz.", "Hata veya eski bilgi bildirildiğinde kaynak üzerinden yeniden kontrol ediyoruz."], disclosure: "Reklam açıklamasını oku",
  },
  en: {
    metaTitle: "Research and Source Policy — VPN Advisor", metaDescription: "How VPN Advisor collects provider information, prioritises sources, handles freshness, comparison fields and limitations.", badge: "Transparent source policy", h1: "How we research and compare VPN information", intro: "VPN Advisor is not a testing laboratory and does not present unperformed speed, streaming or security tests as if they happened. Our goal is to organise verifiable, current information from primary sources wherever possible.", updated: "Last updated", toc: "On this page",
    items: ["1. Core principle", "2. Source hierarchy", "3. Comparison fields", "4. Freshness", "5. Limitations and revenue"], principleTitle: "1. Core principle: sources over claims", principleBody: "We do not turn unverifiable performance claims into scores. Provider statements are treated as provider statements; independent audits and standards sources are identified separately.", sourceTitle: "2. Source hierarchy", sourceIntro: "We prefer the strongest available source and avoid relying on marketing copy when better evidence exists.", sourceCards: [["Primary sources", "Official technical documentation, privacy policies, pricing pages, terms and app-store listings."], ["Independent verification", "Published no-logs audits, security assessments, company or court records, and recognised standards organisations."], ["Secondary sources", "Reliable technical publications and public research when primary sources are incomplete, with the source type made clear."]], fieldsTitle: "3. Comparison fields", fieldsIntro: "Provider profiles use consistent information fields. These are not quality scores.", fields: ["Company and jurisdiction", "Privacy and logging policy", "Independent audits or assurance", "Protocols and technical features", "Device and platform support", "Pricing, renewal and refund terms"], freshnessTitle: "4. Freshness policy", freshnessBody: "Pricing and product features change quickly, so profiles keep a last-checked date where possible. Older dates should trigger verification at the official source.", freshnessItems: ["Prices and promotions are not treated as permanent facts.", "Audit claims are evaluated with publication date and scope.", "Server and country counts are treated as provider data when self-reported.", "Material changes update the page's updatedAt date."], limitsTitle: "5. Limitations and revenue", limitsBody: "VPN performance varies by device, network, country, protocol and time. Public documentation cannot guarantee real-world performance. VPN Advisor may earn revenue from Google AdSense and, in the future, some affiliate links; this should not alter data fields or source selection.", limits: ["We do not claim continuous in-house speed testing.", "We do not guarantee permanent streaming access.", "We do not present provider claims as independent verification.", "We do not guarantee prices will remain unchanged at purchase time.", "Reported errors are rechecked against sources."], disclosure: "Read the advertising disclosure",
  },
  de: {
    metaTitle: "Recherche- und Quellenrichtlinie — VPN Advisor", metaDescription: "Wie VPN Advisor Anbieterinformationen sammelt, Quellen priorisiert, Aktualität behandelt und Vergleichsfelder sowie Einschränkungen dokumentiert.", badge: "Transparente Quellenrichtlinie", h1: "Wie wir VPN-Informationen recherchieren und vergleichen", intro: "VPN Advisor ist kein Testlabor und stellt nicht durchgeführte Geschwindigkeits-, Streaming- oder Sicherheitstests nicht als echte Tests dar. Ziel ist es, überprüfbare und aktuelle Informationen möglichst aus Primärquellen verständlich zu strukturieren.", updated: "Aktualisiert", toc: "Auf dieser Seite",
    items: ["1. Grundprinzip", "2. Quellenhierarchie", "3. Vergleichsfelder", "4. Aktualität", "5. Grenzen und Einnahmen"], principleTitle: "1. Grundprinzip: Quellen statt Behauptungen", principleBody: "Nicht überprüfbare Leistungsbehauptungen werden nicht in Bewertungen umgewandelt. Anbieterangaben bleiben Anbieterangaben; unabhängige Audits und Standardquellen werden separat gekennzeichnet.", sourceTitle: "2. Quellenhierarchie", sourceIntro: "Wir bevorzugen die stärkste verfügbare Quelle und verlassen uns nicht auf Marketingtexte, wenn bessere Belege existieren.", sourceCards: [["Primärquellen", "Offizielle technische Dokumentation, Datenschutzrichtlinien, Preisseiten, Bedingungen und App-Store-Einträge."], ["Unabhängige Verifikation", "Veröffentlichte No-Logs-Audits, Sicherheitsbewertungen, Unternehmens- oder Gerichtsunterlagen und anerkannte Standardorganisationen."], ["Sekundärquellen", "Zuverlässige technische Publikationen und öffentliche Forschung, wenn Primärquellen unvollständig sind; die Quellenart wird kenntlich gemacht."]], fieldsTitle: "3. Vergleichsfelder", fieldsIntro: "Anbieterprofile verwenden einheitliche Informationsfelder. Diese sind keine Qualitätsbewertungen.", fields: ["Unternehmen und Zuständigkeit", "Datenschutz- und Logging-Richtlinie", "Unabhängige Audits oder Prüfungen", "Protokolle und technische Funktionen", "Geräte- und Plattformunterstützung", "Preise, Verlängerung und Erstattung"], freshnessTitle: "4. Aktualitätsrichtlinie", freshnessBody: "Preise und Produktfunktionen ändern sich schnell. Profile enthalten daher möglichst ein letztes Prüfdatum; ältere Angaben sollten bei der offiziellen Quelle verifiziert werden.", freshnessItems: ["Preise und Aktionen gelten nicht als dauerhafte Fakten.", "Auditangaben werden mit Datum und Umfang betrachtet.", "Server- und Länderzahlen gelten als Anbieterangaben, wenn sie selbst gemeldet sind.", "Wesentliche Änderungen aktualisieren das updatedAt-Datum."], limitsTitle: "5. Grenzen und Einnahmen", limitsBody: "VPN-Leistung hängt von Gerät, Netzwerk, Land, Protokoll und Zeitpunkt ab. Öffentliche Dokumentation garantiert keine reale Leistung. VPN Advisor kann Einnahmen aus Google AdSense und künftig aus einigen Affiliate-Links erzielen; dies soll Datenfelder und Quellenwahl nicht verändern.", limits: ["Wir behaupten keine laufenden eigenen Geschwindigkeitstests.", "Wir garantieren keinen dauerhaften Streaming-Zugang.", "Anbieterangaben werden nicht als unabhängige Verifikation dargestellt.", "Preise werden nicht für den Kaufzeitpunkt garantiert.", "Gemeldete Fehler werden anhand von Quellen erneut geprüft."], disclosure: "Werbehinweis lesen",
  },
} as const;

function safeLocale(value: string): Locale { return value === "en" || value === "de" ? value : "tr"; }

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { locale: rawLocale } = await params; const locale = safeLocale(rawLocale); const copy = COPY[locale];
  return { title: copy.metaTitle, description: copy.metaDescription, alternates: localizedAlternates("/metodoloji", locale), openGraph: { title: copy.metaTitle, description: copy.metaDescription, url: absoluteUrl("/metodoloji", locale), type: "article" } };
}

export default async function Page({ params }: Props) {
  const { locale: rawLocale } = await params; const locale = safeLocale(rawLocale); setRequestLocale(locale); const copy = COPY[locale];
  const tocLinks = ["#principle", "#sources", "#fields", "#freshness", "#limits"]; const sourceIcons = [FileText, ShieldCheck, Database]; const fieldIcons = [Building2, ShieldCheck, FileSearch, Database, Smartphone, Tag];
  return <Container size="md" className="py-12 sm:py-16 lg:py-20">
    <header><span className="inline-flex items-center gap-1.5 rounded-full bg-brand-100 px-3 py-1 text-xs font-semibold text-brand-700"><ShieldCheck className="size-3.5" /> {copy.badge}</span><h1 className="mt-4 text-3xl sm:text-4xl lg:text-5xl font-bold tracking-tight text-ink-strong">{copy.h1}</h1><p className="mt-5 text-base sm:text-lg text-ink-muted leading-relaxed">{copy.intro}</p><p className="mt-4 inline-flex items-center gap-1.5 text-xs font-medium text-ink-muted"><CalendarDays className="size-3.5" /> {copy.updated}: <span className="text-ink">8 August 2026</span></p></header>
    <nav aria-label={copy.toc} className="mt-10 rounded-xl border border-border bg-surface-subtle p-5 sm:p-6"><h2 className="flex items-center gap-2 text-sm font-semibold uppercase tracking-wide text-ink-muted"><ListChecks className="size-4" /> {copy.toc}</h2><ul className="mt-4 grid gap-2 sm:grid-cols-2">{copy.items.map((item, index) => <li key={item}><a href={tocLinks[index]} className="flex items-center gap-2 rounded-md px-2 py-1.5 text-sm text-ink hover:bg-brand-50 hover:text-brand-700"><ArrowUpRight className="size-4 shrink-0 text-brand-600" /> {item}</a></li>)}</ul></nav>
    <section id="principle" className="mt-14 scroll-mt-24"><SectionHeading Icon={Scale} title={copy.principleTitle} /><p className="mt-4 text-ink leading-relaxed">{copy.principleBody}</p></section>
    <section id="sources" className="mt-14 scroll-mt-24"><SectionHeading Icon={FileSearch} title={copy.sourceTitle} /><p className="mt-4 text-ink leading-relaxed">{copy.sourceIntro}</p><div className="mt-6 grid gap-4 sm:grid-cols-3">{copy.sourceCards.map(([title, body], index) => { const Icon = sourceIcons[index]; return <div key={title} className="rounded-xl border border-border bg-surface-base p-5 dark:bg-surface-subtle"><Icon className="size-5 text-brand-600" /><h3 className="mt-3 text-sm font-semibold text-ink-strong">{title}</h3><p className="mt-2 text-sm text-ink leading-relaxed">{body}</p></div>; })}</div></section>
    <section id="fields" className="mt-14 scroll-mt-24"><SectionHeading Icon={Database} title={copy.fieldsTitle} /><p className="mt-4 text-ink leading-relaxed">{copy.fieldsIntro}</p><ul className="mt-6 grid sm:grid-cols-2 gap-3">{copy.fields.map((item, index) => { const Icon = fieldIcons[index]; return <li key={item} className="flex items-center gap-3 rounded-lg border border-border bg-surface-base p-4 dark:bg-surface-subtle"><Icon className="size-4 text-brand-600 shrink-0" /><span className="text-sm text-ink-strong">{item}</span></li>; })}</ul></section>
    <section id="freshness" className="mt-14 scroll-mt-24"><SectionHeading Icon={RefreshCw} title={copy.freshnessTitle} /><p className="mt-4 text-ink leading-relaxed">{copy.freshnessBody}</p><ul className="mt-5 space-y-3">{copy.freshnessItems.map((item) => <li key={item} className="flex items-start gap-3 rounded-lg border border-border bg-surface-base p-4 dark:bg-surface-subtle"><CalendarDays className="size-4 text-brand-600 shrink-0 mt-0.5" /><span className="text-sm text-ink leading-relaxed">{item}</span></li>)}</ul></section>
    <section id="limits" className="mt-14 scroll-mt-24"><SectionHeading Icon={Eye} title={copy.limitsTitle} /><p className="mt-4 text-ink leading-relaxed">{copy.limitsBody}</p><div className="mt-6 rounded-xl border border-border bg-surface-base p-5 dark:bg-surface-subtle"><ul className="space-y-2.5 text-sm text-ink">{copy.limits.map((item) => <li key={item} className="flex items-start gap-2"><AlertTriangle className="size-4 text-amber-600 shrink-0 mt-0.5" /><span>{item}</span></li>)}</ul><Link href="/reklam-aciklamasi" className="mt-5 inline-flex items-center gap-1 text-sm font-semibold text-brand-700 hover:underline">{copy.disclosure} <ExternalLink className="size-3.5" /></Link></div></section>
  </Container>;
}

function SectionHeading({ Icon, title }: { Icon: typeof ShieldCheck; title: string }) { return <h2 className="flex items-center gap-2 text-2xl sm:text-3xl font-bold tracking-tight text-ink-strong"><Icon className="size-6 text-brand-600 shrink-0" /> {title}</h2>; }
