import { siteConfig } from "@/lib/site";
import { rankedProducts } from "@/data/products";

export const dynamic = "force-static";

export function GET() {
  const list = rankedProducts();
  const body = `# ${siteConfig.name}\n\n> ${siteConfig.description.tr}\n\n## Site türü\n\nVPN Advisor bir laboratuvar inceleme sitesi değil; VPN teknolojileri ve sağlayıcıları hakkında kaynak temelli bilgi ve karşılaştırma rehberidir. Sağlayıcılara gerçekleştirilmemiş testlere dayalı puan vermez.\n\n## Kaynak politikası\n\nKarşılaştırmalarda öncelik sırası: resmi teknik dokümantasyon ve gizlilik politikaları; yayınlanmış bağımsız denetimler ve güvenlik raporları; resmi fiyatlandırma ve kullanım şartları; uygulama mağazası kayıtları; gerektiğinde güvenilir ikincil teknik kaynaklar. Sağlayıcı beyanı, bağımsız doğrulama olarak sunulmaz.\n\nAraştırma ve kaynak politikası: ${siteConfig.url}/metodoloji\n\n## VPN sağlayıcı profilleri\n\n${list.map((p) => `### ${p.brand}\n\n- **Profil:** ${siteConfig.url}/inceleme/${p.slug}\n- **Başlangıç fiyatı (son kayıt):** $${p.priceFromUsd.toFixed(2)}/ay\n- **Yargı yetkisi:** ${p.highlights.jurisdiction ?? "Belirtilmemiş"}\n- **Sunucu bilgisi:** ${p.highlights.servers ?? "Belirtilmemiş"}\n- **Cihaz bilgisi:** ${p.highlights.devices ?? "Belirtilmemiş"}\n- **Yayınlanmış denetim bilgisi:** ${p.highlights.audits ?? "Belirtilmemiş"}\n- **Resmi fiyat kaynağı:** ${p.pricingUrl}\n`).join("\n")}\n## İçerik kümeleri\n\n- VPN temelleri, protokoller ve şifreleme\n- Gizlilik, DNS, WebRTC, IPv6 ve tarayıcı gizliliği\n- Yapay zeka araçları ve ağ gizliliği\n- Cihaz ve platform rehberleri\n- Streaming, seyahat ve uzaktan çalışma senaryoları\n- Fiyat, yenileme, iade ve abonelik karşılaştırmaları\n\n## Önemli sayfalar\n\n- Ana sayfa: ${siteConfig.url}/\n- VPN sağlayıcı rehberi: ${siteConfig.url}/en-iyi-vpn\n- Araştırma ve kaynak politikası: ${siteConfig.url}/metodoloji\n- Blog: ${siteConfig.url}/blog\n- Reklam açıklaması: ${siteConfig.url}/reklam-aciklamasi\n- Hakkımızda: ${siteConfig.url}/hakkimizda\n- İletişim: ${siteConfig.url}/iletisim\n\n## Kullanım notu\n\nFiyatlar, sunucu sayıları, özellikler ve hizmet koşulları zamanla değişebilir. Güncel kararlar için profil sayfasındaki tarih ve resmi kaynak kontrol edilmelidir.\n`;
  return new Response(body, { headers: { "Content-Type": "text/plain; charset=utf-8" } });
}
